### ISSUE TITLE
Error ```insufficient privileges``` when using configmap

### ISSUE THREAD

**Issue by tuxpeople** [ezienecker/grafana-sidecar-folder-sample#2]
Hi

I tried it this way, but I'm struggling a bit.

This is my config map:
https://github.com/tuxpeople/k8s-homelab/blob/master/cluster/apps/media/plex-exporter/grafana-dashboard.yaml

And this my Grafana deployment:
https://github.com/tuxpeople/k8s-homelab/blob/master/cluster/apps/monitoring/grafana/helm-release.yaml

I'm ending up with this error, saying me that grafana has not sufficient permissions on a folder Grafana created itself:
```
$ kubectl logs -n monitoring grafana-c6df564f9-ks4mr -c grafana-sc-dashboard 
[...]
[2021-10-25 11:49:41] Working on ADDED configmap media/plex-exporter-dashboard
[2021-10-25 11:49:41] Found a folder override annotation, placing the plex-exporter-dashboard in: /var/lib/grafana/dashboards/fun
[2021-10-25 11:49:41] Error: insufficient privileges to create /var/lib/grafana/dashboards/fun. Skipping plex-exporter-dashboard.json.
[2021-10-25 11:49:41] Received unknown exception: unsupported operand type(s) for |=: 'bool' and 'NoneType'

Traceback (most recent call last):
  File "/app/resources.py", line 237, in _watch_resource_loop
    _watch_resource_iterator(*args)
  File "/app/resources.py", line 216, in _watch_resource_iterator
    files_changed |= _process_config_map(dest_folder, item, resource, unique_filenames, enable_5xx,
  File "/app/resources.py", line 126, in _process_config_map
    files_changed |= _iterate_data(
  File "/app/resources.py", line 153, in _iterate_data
    files_changed |= _update_file(
TypeError: unsupported operand type(s) for |=: 'bool' and 'NoneType'
[...]
```

**Comment by tuxpeople** [comment]
Looks like the sidecar uses `/tmp/grafana` and I tried it to fix it like this:
https://github.com/tuxpeople/k8s-homelab/commit/fd817f0720ac684bb56e2275a17ac757e5f41a6f

But I failed. I'm only having the sidecar dashboard then. Am I'm right that I'm not abele to mix sidecar and non sidecar dashboards in the same folder?

**Comment by ezienecker** [comment]
First of all. I think the question makes more sense on Stackoverflow than here. More people see it there and they can certainly help you faster there.

What makes you think that it selects `tmp/grafana` as folder? When I run `helm show values stable/grafana` I see that ` /tmp/dashboards` is set as default.

Did you get the example to work in a minikube, without flux etc?

You can check in the sidecar log if grafana picked some configmaps/dashboards

**Comment by tuxpeople** [comment]
Hi Emanuel

First of all, thanks for replying. I highly appreciate this.

Your probably right, and my issue here was just kind of "shoot from the hip" as I took the informations from here and I thought there may be a chance you also stumbled upon this.

But: Looks like I solved it. Just in case you are interested:

Dashboards downloaded by the helm chart are always in `/var/lib/grafana/dashboards`. At least I wasn't able to change this. Changing the path in the `dashboardproviders.yaml` doesn't work, because the downloader initcontainer still uses `/var/lib/grafana/dashboards` and would then start to complain about being not able to use this directory.

By default, the sidecar used for collecting the dashboards from configmaps is using `/tmp/dashboards`. You can change that behavior in values (see [here](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L657-L658)) but it doesn't work to change that to `/var/lib/grafana/dashboards`.

That beeing sayed, I noticed that I see the imported dashboards from the sidecar coming from `/tmp/dashboards`, but not in the (sub)folder they have been downloaded to. After carefully readying my values again and comparing the to the annotated default ones, I found a pretty small thing which actually fixed it all:
https://github.com/tuxpeople/k8s-homelab/commit/7eadaaa8632f20f383dadedbac8a537f4aa700b4

The sidecar creates it's own provider, using `/tmp/dashboards`. Therefore, those dashboards also show up. As soon as I corrected the use of `foldersFromFilesStructure`, they also showed up in the right folder in the UI. Folder `fun` in the UI now contains the dashboards from `/tmp/dashboards/fun` and `/var/lib/grafana/dashboards/fun`

Kind regards
Thomas
